sudo: required

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.15.0

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - cp env.tmpl .env

script:
  - docker-compose up -d

notifications:
  email:
    recipients:
    - rodrigodadamos@gmail.com

# deploy:
#   # deploy develop to the staging environment
#   - provider: heroku
#     api_key: $SECRET_USER_KEY
#     app: testeci
#     on: master
  # deploy master to production
  # - provider: heroku
  #   api_key: $SECRET_USER_KEY
  #   app: testeci
  #   on: master
