version: '3'
services:
  db:
    image: postgres
    environment:
        POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
        POSTGRES_DB: "${POSTGRES_DB}"
        POSTGRES_USER: "${POSTGRES_USER}"
    ports:
      - 5000:5432
  app:
    image: pretevent/pretevent:app
    deploy:
      replicas: 2
    ports:
      - "80:80"
    depends_on:
      - db
  web1:
    image: pretevent/pretevent:web1
    deploy:
      replicas: 2
    ports:
      - "8000:8000"
    depends_on:
      - db
  web2:
    image: pretevent/pretevent:web2
    deploy:
      replicas: 2
    ports:
      - "8001:8000"
    depends_on:
      - db
  web3:
    image: pretevent/pretevent:web3
    deploy:
      replicas: 2
    ports:
      - "8002:8000"
    depends_on:
      - db
