version: '3'
services:
  db:
    image: postgres
    environment:
        POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
        POSTGRES_DB: "${POSTGRES_DB}"
        POSTGRES_USER: "${POSTGRES_USER}"
    ports:
      - 5000:5432
  app:
    build: ./front-end/pret-event/
    image: pretevent/pretevent:app
    volumes:
      - ./:/src/app/
    ports:
      - "8080:80"
    depends_on:
      - db
  web1:
    build: ./service/mc1/
    image: pretevent/pretevent:web1
    command: /bin/sh ./boot.sh
    volumes:
      - ./service/mc1/:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  web2:
    build: ./service/mc2/
    image: pretevent/pretevent:web2
    command: /bin/sh ./boot.sh
    volumes:
      - ./service/mc2/:/code
    ports:
      - "8001:8000"
    depends_on:
      - db
  web3:
    build: ./service/mc3/
    image: pretevent/pretevent:web3
    command: /bin/sh ./boot.sh
    volumes:
      - ./service/mc3/:/code
    ports:
      - "8002:8000"
    depends_on:
      - db
