version: '3'
services:
  db:
    image: postgres
    environment:
        POSTGRES_PASSWORD: "postgres"
        POSTGRES_DB: "postgres"
        POSTGRES_USER: "postgres"
    ports:
      - 5432:5432
  app:
    build: ./front-end/pret-event
    volumes:
      - ./front-end/pret-event:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4500:4200"
  web1:
    build: ./service/mc1/
    image: pretevent/web1
    command: /bin/sh ./boot.sh
    volumes:
      - ./service/mc1/:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  web2:
    build: ./service/mc2/
    image: pretevent/web2
    command: /bin/sh ./boot.sh
    volumes:
      - ./service/mc2/:/code
    ports:
      - "8001:8000"
    depends_on:
      - db
  web3:
    build: ./service/mc3/
    image: pretevent/web3
    command: /bin/sh ./boot.sh
    volumes:
      - ./service/mc3/:/code
    ports:
      - "8002:8000"
    depends_on:
      - db
