version: '3'
services:
  db:
    image: postgres
  app:
    image: pretevent/app
    ports:
      - "80:80"
  web1:
    image: pretevent/web1
    ports:
      - "8000:8000"
    depends_on:
      - db
  web2:
    image: pretevent/web2
    ports:
      - "8001:8000"
    depends_on:
      - db
  web3:
    image: pretevent/web3
    ports:
      - "8002:8000"
    depends_on:
      - db
